version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - dupl
    - gocyclo
    - lll
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
        path: api/v1/store_test.go
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
