run:
  timeout: 8m
  allow-parallel-runners: true

linters:
  enable:
    - dupl
    - gocyclo
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam

issues:
  exclude-dirs:
    - third_party
    - builtin
    - examples
  exclude-rules:
    - path: api/
      linters:
        - lll
    - path: api/v1/store_test.go
      linters:
        - dupl
    - path: internal/
      linters:
        - dupl
        - lll
  exclude-generated: lax
