apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shopware-operator
    app.kubernetes.io/part-of: shopware-operator
    app.kubernetes.io/managed-by: kustomize
  name: le-shopware-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: le-shopware-operator
subjects:
- kind: ServiceAccount
  name: shopware-operator
