---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shopware-operator
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - shop.shopware.com
  resources:
  - storedebuginstances
  - storeexecs
  - storesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shop.shopware.com
  resources:
  - storedebuginstances/finalizers
  - storeexecs/finalizers
  - stores/finalizers
  - storesnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - shop.shopware.com
  resources:
  - storedebuginstances/status
  - storeexecs/status
  - stores/status
  - storesnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - shop.shopware.com
  resources:
  - stores
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
