# permissions for end users to view stores.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: store-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shopware-operator
    app.kubernetes.io/part-of: shopware-operator
    app.kubernetes.io/managed-by: kustomize
  name: store-viewer-role
rules:
- apiGroups:
  - shop.shopware.com
  resources:
  - stores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shop.shopware.com
  resources:
  - stores/status
  verbs:
  - get
