# permissions for end users to view storesnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: storesnapshot-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: shopware-operator
    app.kubernetes.io/part-of: shopware-operator
    app.kubernetes.io/managed-by: kustomize
  name: storesnapshot-viewer-role
rules:
- apiGroups:
  - shop.shopware.com
  resources:
  - storesnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shop.shopware.com
  resources:
  - storesnapshots/status
  verbs:
  - get
