# The name of this file is used in the helm charts repo for octo-sts.
# Please keep that in mind if you want to rename this file.
name: Release Tag version

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  goreleaser:
    runs-on: runs-on=${{ github.run_id }}/runner=sw-amd64/cpu=8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Cache Go build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.5
            network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create resources for release
        run: |
          make resources path=release
          make licenses path=release

      - name: Run goreleaser on release branch
        id: goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update release with kube generated files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
          file: release/*

  release-helm-chart:
    runs-on: runs-on=${{ github.run_id }}/runner=sw-amd64/cpu=1
    needs: [goreleaser]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - uses: octo-sts/action@v1.0.0
        id: octo-sts
        with:
          scope: shopware/helm-charts
          identity: shopware-operator

      - name: make pr on helm-charts for this release
        run: |
          make manifests
          tag=${{ github.ref_name }}
          git clone https://oauth2:${GITHUB_TOKEN}@github.com/shopware/helm-charts.git
          rm -rf helm-charts/charts/shopware-operator
          make helm version=${tag} path=helm-charts/charts/shopware-operator
          cd helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout -b auto-release-${tag}
          git add .
          git commit -m "New shopware operator image"
          git push origin auto-release-${tag}
          gh pr create --title "Autorelease from shopware operator" --body "Auto pr from shopware operator" --head "auto-release-${tag}" --base main --reviewer shopware/product-paas
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
